### ISSUE TITLE
How to change blog avatar in listing?

### ISSUE THREAD

**Issue by pwojnowski** [jirkapinkas/java-blog-aggregator-boot#1]
I've got a blog at topjavablogs (http://www.topjavablogs.com/blog/java-by-example) and don't like that avatar. How can I change it?

Sorry that I write here, but I haven't seen any feedback form nor email address on topjavablogs.

**Comment by jirkapinkas** [comment]
Sure, no problem. Just send me an email with the icon and I'll upload it (currently only me - the administrator - can change that). Preferable format: PNG, 50x50 px, but you can send me any image file and I'll adjust it. My email: jirka.pinkas@gmail.com
