### ISSUE TITLE
Signup/login issue

### ISSUE THREAD

**Issue by codenameone** [jirkapinkas/java-blog-aggregator-boot#3]
Hopefully his is the right place to post it, I wanted to add our blog and signed up. I didn't get a confirmation email (which I assume was sent) and can't login.

**Comment by jirkapinkas** [comment]
Hello, I have no idea what went wrong, because I just tested it and everything works. But if you want to submit this blog: https://www.codenameone.com/blog/ then don't bother, I won't approve it because it's focus is different than this website's focus.
