### ISSUE TITLE
Issue with registration + login

### ISSUE THREAD

**Issue by rieckpil** [jirkapinkas/java-blog-aggregator-boot#7]
Hi,

I recently tried to register a new account and once I get the green notification that I successfully registered, I am not able to log in and get redirected to https://www.topjavablogs.com/login?error. In addition, I tried it with a different email and it did not work either.

Is there any confirmation mail to be received?

Kind regards,
Phil

**Comment by rieckpil** [comment]
can someone help?

**Comment by rieckpil** [comment]
someone available?

**Comment by kasramp** [comment]
I had the same issue. They don't confirmation email or anything. I managed to login by using my **username** instead of **email address**.

**Comment by rieckpil** [comment]
@kasramp thank you very much, using the username works 🎉
